### ISSUE TITLE
IRS 2023 - schema?

### ISSUE THREAD

**Issue by zapafta** [rgl/ValidateSchema#1]
Ola,

Reparei que tens um repositorio com os schemas do IRS Portugues
https://github.com/rgl/irs-schemas

<Modelo3IRSv2023 xmlns="http://www.dgci.gov.pt/2009/Modelo3IRSv2023" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" versao="1" xsi:schemaLocation="http://www.dgci.gov.pt/2009/Modelo3IRSv2023 Modelo3IRSv2023.xsd">

Sabes se ja se encontra disponivel para o modelo Modelo3IRSv2023 ?
Tentei ver no site das finanças, mas parece-me que os serviços estão em baixo.

**Comment by rgl** [comment]
Não faço idea. Desde o último commit, nunca mais mexi nisso.
